/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/engdb.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.engdb.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module engdb.yang */
public class engdb extends ConfNamespace {
    public static final int hash = 1115197344;
    public int hash() {
        return engdb.hash;
    }

    public static final String id = "http://com/example/engdb";
    public String id() {
        return engdb.id;
    }

    public static final String uri = "http://com/example/engdb";
    public String uri() {
        return engdb.uri;
    }

    public static final String prefix = "engdb";
    public String prefix() {
        return engdb.prefix;
    }

    public engdb() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _item = 1470352621;
    public static final String _item_ = "item";
    public static final int    _test_stats = 655854080;
    public static final String _test_stats_ = "test-stats";
    public static final int    _i = 1541010383;
    public static final String _i_ = "i";
    public static final String callpoint_test_stats_cp = "test-stats-cp";
}
